### ISSUE TITLE
Bug: flickering popover

### ISSUE THREAD

**Issue by martuk-and** [material-extended/popover#54]
Bug
Open https://uixd.co.uk/open-source-software/material-extended/demo/ in Chrome Browser.
Move mouse over "Hover me". Do not move mouse during and after opening popover. Popover will open and close every second.

**Comment by joejordanbrown** [comment]
@martuk-and 

That demo needs to be rebuilt from the current version because It's using the very early Alpha version of this project. 

Thanks for reminding me about that example, I will add it to my todo list to update that demo every time I release a new version to keep that up to date going forward.

If you can provide an example on StackBlitz of this still happening on the latest version, I'd be happy to look into this for you.

**Comment by diosney** [comment]
It happens to me with Angular ~10.0.1 and `"@material-extended/mde": "^3.0.3"`.

If I move the mouse inside the popover or quickly press Tab, then it stays as it should.

**Comment by joejordanbrown** [comment]
@diosney 

Please share a Stackblitz example with this issue and I'll take a look. 

I've not seen that issue on any recent version on our internal projects.
